import './globals.css'
import style from "./page.module.css"
import { Inter } from 'next/font/google'
import Nav from './nav/page'
import FooterComponents from './FooterComponents/page'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>
          next tutorial
        </title>
      </head>
      <body className={inter.className}>
        <div className={style.container}>
          <Nav />
          {children}
          <FooterComponents />
        </div>
      </body>
    </html>
  )
}